### ISSUE TITLE
documentation: type in constructoroptions

### ISSUE THREAD

**Issue by gregprodind** [badbatch/cachemap#35]
Hello,

what is the meaning and use of type in constructoroptions? 

https://github.com/badbatch/cachemap/blob/master/packages/core/docs/interfaces/constructoroptions.md 

The example uses 'someType'. Could you explain its use and expected values?

Thank you!

**Comment by dylanaubrey** [comment]
hey... thanks for the issue!... yeh, this type prop is used to identify groups of cachemap instances so they can be centrally controlled by the controller package within an application. It is detailed, to some extent, here: https://github.com/badbatch/cachemap#controlling-multiple-instances

I use the feature in order to start the reaper within each cachemap of a given type, rather than having each one reaper start up automatically on instantiation. At the moment, you can start and stop reapers and clear all caches using the controller.

I use these features most for unit and integration testing within other libraries that use cachemap, but I do use the start /stop reapers feature within graphql servers that have a lot of instances of cachemaps. Does that help?

**Comment by gregprodind** [comment]
Got it! Thanks!
